// packages/vue/src/components/Link.vue
<script setup lang="ts">
import { twMerge } from "tailwind-merge";

import { useAttrs } from "vue";

const attrs = useAttrs();
</script>

<template>
  <a
    :class="
      twMerge(
        'bg-transparent text-primary hover:underline underline-offset-3',
        attrs.class as string | undefined,
      )
    "
    v-bind="attrs"
  >
    <slot />
  </a>
</template>

// packages/react/src/components/Link/Link.tsx
import { cn } from "@nuvra-ui/utils";

export function Link({
  className,
  children,
  ...props
}: React.AnchorHTMLAttributes<HTMLAnchorElement>) {
  return (
    <a
      className={cn(
        "text-primary underline-offset-4 hover:underline",
        className,
      )}
      {...props}
    >
      {children}
    </a>
  );
}
