// packages/vue/src/components/Link.vue
<script setup lang="ts">
import { twMerge } from "tailwind-merge";

import { useAttrs } from "vue";

const attrs = useAttrs();
</script>

<template>
  <a
    :class="
      twMerge(
        'bg-transparent text-primary hover:underline underline-offset-3',
        attrs.class as string | undefined,
      )
    "
    v-bind="attrs"
  >
    <slot />
  </a>
</template>

// src/components/Link/Link.tsx
import React from "react";
import { twMerge } from "tailwind-merge";

const Link = ({ className, children, ...props }: React.ComponentProps<"a">) => {
  return (
    <a
      className={twMerge(
        "bg-transparent text-primary hover:underline underline-offset-3",
        className
      )}
      {...props}
    >
      {children}
    </a>
  );
};

export { Link };
